import cv2
img=cv2.imread('len.jpg')
sclae_percent=50
width=int(img.shape[1]*sclae_percent/100)
height=int(img.shape[0]*sclae_percent/100)
dim=(width,height)
resize=cv2.resize(img,dim,cv2.INTER_AREA)
resized1=cv2.resize(img,dim,cv2.INTER_CUBIC)
resized2=cv2.resize(img,dim,cv2.INTER_LINEAR)
resized3=cv2.resize(img,dim,cv2.INTER_NEAREST)
print('Original Dimensions:',img.shape)
print('Resized Dimensions:',resize.shape)
print('Cubic Dimensions:',resized1.shape)
print('Linear Dimensions:',resized2.shape)
print('Nearest Dimensions:',resized3.shape) 
cv2.imshow('original',img)
cv2.imshow('area',resize)
cv2.imshow('cubic',resized1)
cv2.imshow('linear',resized2)
cv2.imshow('nearest',resized3)
cv2.waitKey(0)
cv2.destroyAllWindows()